DROP TABLE t_sip_bairro CASCADE CONSTRAINTS;

DROP TABLE t_sip_cidade CASCADE CONSTRAINTS;

DROP TABLE t_sip_dependente CASCADE CONSTRAINTS;

DROP TABLE t_sip_depto CASCADE CONSTRAINTS;

DROP TABLE t_sip_endereco CASCADE CONSTRAINTS;

DROP TABLE t_sip_estado CASCADE CONSTRAINTS;

DROP TABLE t_sip_funcionario CASCADE CONSTRAINTS;

DROP TABLE t_sip_funcionario_endereco CASCADE CONSTRAINTS;

DROP TABLE t_sip_implantacao CASCADE CONSTRAINTS;

DROP TABLE t_sip_projeto CASCADE CONSTRAINTS;

DROP TABLE t_sip_tipo_endereco CASCADE CONSTRAINTS;
